- name: Install Filebeat
  apt:
    name: filebeat
    state: present

- name: Copy Filebeat configuration file
  copy:
    src: files/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
  notify: Restart Filebeat
