---
- name: Install Apache on Ubuntu
  become: yes  # Use sudo to execute commands with elevated privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"  # Ensure this task only runs on Debian-based systems (e.g., Ubuntu)

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes  # Ensure Apache starts at boot
