---
- name: configure filebeat
  hosts: elk_server
  become: yes
  tasks:
    - name: configure filebeat
      include_role:
        name: filebeat
  handlers:
    - include: roles/filebeat/handlers/main.yml

