filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log  # Replace with the actual path to your application's log files
    fields:
      application: app1  # Specify the application name for differentiation in Logstash

output.logstash:
  hosts: ["18.222.226.233:5044"]  # Replace with the hostname or IP address of your Logstash server and the correct port

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
